services:

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

  backend:
    image: anas999/backend:latest
    container_name: backend-api
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: ${CLIENT_URL}
    networks:
      default:
        aliases:
          - backend-svc
    depends_on:
      - mysql
    ports:
      - "5000:5000"

  frontend:
    image: anas999/frontend:latest
    container_name: frontend-react
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data:
